library(docopt)
"dens_plt.R 
usage: docopt_test.R (-i=infile_prefix) [options]

Options:
-i --inpref=<file>       prefix of the files generated by metagene_agg.py
-o --outpref=<file>      prefix for output plot files [default: --inpref]
-l --leftlim=<nt>        left plot border relative anchor, in nt [default: -100]
-r --rightlim=<nt>       right plot border relative anchor, in nt [default: +50]
-t --toplim=<nt>         top plot border for fraglen vs pos, in nt [default: 100]
-b --bottomlim=<nt>      bottom plot border for fraglen vs pos, in nt [default: 0]
--uci=<pc>               upper bootstrapped percentile [default: 97.5]
--lci=<pc>               lower bootstrapped percentile [default: 2.5]
--pdfwidth=<in>          pdf width, inches [default: 7]
--pdfheight=<in>         pdf height, inches [default: 7]
--anchor=<anchor>        point around which ORFs were anchored by metagene_agg.py [default: start]
" -> doc
options = docopt(doc = doc)
INFN_PREFIX = options$inpref
OUTFN_PREF = INFN_PREFIX
if(options$outpref!='--inpref'){
  OUTFN_PREF = options$outpref
}
STFQ_FN = paste0(INFN_PREFIX,'_strt.txt')
ENFQ_FN = paste0(INFN_PREFIX, '_end.txt')
STLNFQ_FN = paste0(INFN_PREFIX, '_jnt.txt')
ROI=c(as.numeric(options$leftlim), as.numeric(options$rightlim))
if(ROI[2] - ROI[1] < 8){
  print('Error: plots must be over 8 nt wide.')
  quit()
}

FLEN_LIM = c(as.numeric(options$bottomlim), as.numeric(options$toplim))
if(FLEN_LIM[2] - FLEN_LIM[1] < 1 ){
  print('Error: top plot border must be greater than bottom border')
  quit()
}
UP_CI=as.numeric(options$uci)/100
LO_CI=as.numeric(options$lci)/100
OUTWIDTH = as.numeric(options$pdfwidth)
OUTHEIGHT = as.numeric(options$pdfheight)
ANCHOR=options$anchor

library(ggplot2)
library(plyr)
library(dplyr)

cnms=c('pos', 'nonperm', paste0('bs_', c(1:10000)))
stfrq = read.table(file=STFQ_FN, header = F,sep = '\t',quote = '',comment.char = '')
colnames(stfrq)=cnms[1:ncol(stfrq)]
enfrq = read.table(file=ENFQ_FN, header = F,sep = '\t',quote = '',comment.char = '')
colnames(enfrq)=cnms[1:ncol(enfrq)]
slfrq = read.table(file=STLNFQ_FN, header = F,sep = '\t',quote = '',comment.char = '')
colnames(slfrq)=c('pos', paste0('fl_',0:(ncol(slfrq)-2)))

######################################
# Marginal density / bootstrapped plot
######################################

normed_bstrap <- function(perm_res2, upperCI = UP_CI, lowerCI = LO_CI, binwidth=1){
  posrange = min(perm_res2$pos):max(perm_res2$pos)
  perm_res2['bin_pos'] = perm_res2$pos - ((perm_res2$pos - posrange[1]) %% binwidth)
  datacols = !(colnames(perm_res2) %in% c('bin_pos', 'pos'))
  perm_res2 = ddply(.data=perm_res2, .variables = 'bin_pos', .fun = function(x, datacols2){
    cmeans = colSums( x[,datacols2] ) / nrow(x)
    mat = matrix(rep(cmeans, each = nrow(x)), nrow = nrow(x))
    colnames(mat)=colnames(x)[datacols]
    pos=x$pos
    dout = cbind(pos, as.data.frame(mat))
    return( dout)
  },
  datacols)
  perm_resN = perm_res2[,which(!colnames(perm_res2) %in% c('pos', 'bin_pos'))]
  perm_resN = t(t(perm_resN)/(pmax(1,colSums(perm_resN)))) # if zero counts, set colsums of perm_resN to 1
  nonperm_N=perm_resN[,colnames(perm_resN) == 'nonperm']
  perm_resN=perm_resN[, which(!colnames(perm_resN) == 'nonperm')] # remove non-permuted column, stored normed data from this in nonperm_N vector
  perm_msd = data.frame( pos = posrange,
                         mean=rowMeans(perm_resN),
                         upperCI=apply(perm_resN, MARGIN = 1, FUN = function(x){return(quantile(x, upperCI))}  ),
                         lowerCI=apply(perm_resN, MARGIN = 1, FUN = function(x){return(quantile(x, lowerCI))}  )
  )
  perm_msd$nonperm=nonperm_N
  nr = nrow(perm_msd)
  mirror_msd = data.frame(pos = perm_msd$pos[c(1:nr,nr:1)], CIs = c(perm_msd$upperCI[1:nr], perm_msd$lowerCI[nr:1]))
  return(list(perm_msd, mirror_msd, perm_res2))
}

make_breaks <- function(ROI, howmany = 7, br_minor = 5){
  for(tick_spacing in c(1,5,10,20,25,50,100,200,250,500,1000,2000,2500,5000)){
    if (tick_spacing * howmany < (ROI[2] - ROI[1])){
      majbreaks = seq(-1000, 5000, by = tick_spacing)
      minbreaks = seq(-1000, 5000, by = tick_spacing/br_minor)
    }
  }
  return(list(majbreaks, minbreaks))
}

insert_minor <- function(major_labs, n_minor) {
  labs <-  c( sapply( major_labs, function(x) c(x, rep("", 4) ) ) )
  return(labs[1:(length(labs)-n_minor)])
}

br_minor=5 # <---- EDIT?
stx<-normed_bstrap(perm_res2 = stfrq)
stt_msd=stx[[1]]
stt_mir=stx[[2]]
enx<-normed_bstrap(perm_res2 = enfrq)
end_msd=enx[[1]]
end_mir=enx[[2]]

ticks = make_breaks(ROI=ROI, howmany = 5 , br_minor = br_minor)

# make plot of mean-bootstrapped vals with line error bars
if(F){
  gr1 = ggplot(stt_msd) +
    geom_vline(xintercept = ticks[[1]], col = '#DFDFDD', size=0.25) +  # artificial vertical gridlines
    geom_segment(aes(x=pos,xend=pos, y=lowerCI, yend=upperCI), col='#788899') +
    geom_line(aes(x=pos,y=nonperm)) + #, col=linecol) +
    scale_x_continuous(limits=ROI, breaks = ticks[[2]], labels = insert_minor(ticks[[1]], br_minor - 1) )  +
    labs(x = 'pos', y = 'Frequency') + theme_bw() + 
    theme(panel.grid.minor = element_blank(), panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(colour = '#DFDFDD', size=0.2)) + 
    ggtitle(label = 'Marginal Density - FP start')
}

# make polygon plot
max_y_end  = max( end_mir[ end_mir$pos >= min(ROI) & end_mir$pos <= max(ROI),  ]$CIs , na.rm = T)
max_y_start = max( stt_mir[ stt_mir$pos >= min(ROI) & stt_mir$pos <= max(ROI),  ]$CIs , na.rm = T)
max_y = max(c(max_y_start, max_y_end))
gr2 = ggplot() +
  geom_polygon(data = stt_mir[ stt_mir$pos >= min(ROI) & stt_mir$pos <= max(ROI),  ],
               aes(x=pos, y=CIs), fill = "#FF0000", alpha=0.25)+
  #geom_line(data =stt_msd, aes(x=pos,y=mean), col="#FF0000", size=0.8) +
  geom_line(data =stt_msd, aes(x=pos,y=nonperm), col="#FF0000", size=0.8) +
  geom_polygon(data = end_mir[ end_mir$pos >= min(ROI) & end_mir$pos <= max(ROI),  ],
               aes(x=pos, y=CIs), fill = "#0000FF", alpha=0.25)+
  #geom_line(data =end_msd, aes(x=pos,y=mean), col="#0000FF", size=0.8) +
  geom_line(data =end_msd, aes(x=pos,y=nonperm), col="#0000FF", size=0.8) +
  scale_x_continuous(limits=c(min(ROI),max(ROI)), breaks = ticks[[2]], labels = insert_minor(ticks[[1]], br_minor - 1) )  +
  scale_y_continuous(limits=c(0,max_y)) +
  labs(x = 'pos', y = 'Frequency') + theme_bw()+ 
  theme(panel.grid = element_blank()) + 
  ggtitle(label = 'Marginal FP density, gene-wise bootstrapping')

pdf(file=paste0(OUTFN_PREF, '_mrgn_dens.pdf'), width = OUTWIDTH, height=OUTHEIGHT)
  print(gr2)
dev.off()


#######################################
# HEATMAP
#######################################

plot_joint_frq <- function(dens_df, xlim_s=c(-100,100), ylim_s=c(0,100), legend=TRUE, legend_breaks = c(3.2, 10,31.6,100,316,1000, 3162, 10000), legend_size=0.5,
                          maxdens_within_xlim = FALSE, add_tickbreaks = TRUE, zeroline=F, ybreak=5) {
  br_minor = 5
  ticks = make_breaks(ROI=xlim_s, howmany = 7, br_minor = br_minor)
  interval = 10
  b = as.integer(xlim_s/interval)
  b = c(b[1]:b[2]) * interval
  
  if(maxdens_within_xlim){
    dens_df=dens_df[dens_df$pos >= (xlim_s[1]-1) & dens_df$pos <= (xlim_s[2]+1), ]
  }
  library(reshape2)
  dens_long = melt(dens_df, id.vars = 'pos', variable.name = 'frag_len', value.name = 'frequency')
  dens_long$frag_len=as.numeric(substr(x=as.character(dens_long$frag_len), start=4, stop=99))
  
  gr <- ggplot(dens_long)  + # ylim(0,100) + # xlim(xlim_s[1], xlim_s[2]) +
    geom_tile(aes(x=pos, y=frag_len, fill=frequency)) + 
    scale_fill_gradientn(trans="log", colours=rainbow(4)[4:1], breaks = legend_breaks, na.value = 'white') +
    labs(title = 'FP Length vs Position on mRNAs', x = paste0('Position on mRNA relative to ', ANCHOR), y = 'FP length (nt)') +
    #facet_wrap(~sample_label, nrow=4) +
    scale_x_continuous( breaks = ticks[[1]], limits = xlim_s) +
    scale_y_continuous(breaks = seq(from = floor(ylim_s[1]/ybreak)*ybreak, to = ceiling(ylim_s[2]/ybreak)*ybreak, by = ybreak), limits=ylim_s) +
    coord_cartesian(xlim = c(xlim_s[1]+1, xlim_s[2]), ylim=ylim_s) +
    theme_bw() 
  if(add_tickbreaks){
    gr <- gr + scale_x_continuous(breaks = ticks[[2]], labels = insert_minor(ticks[[1]], br_minor - 1))
    gr <- gr + scale_y_continuous(minor_breaks = seq(from = 0, to = 100, by = 5), 
                                  breaks = seq(from = floor(ylim_s[1]/ybreak)*ybreak, to = ceiling(ylim_s[2]/ybreak)*ybreak, by = ybreak), limits=ylim_s)
  }
  if(zeroline){
    gr=gr+geom_vline(aes(xintercept=0), linetype = "dotted", colour = "purple") 
  }
  if (legend){
    gr <- gr + theme(  axis.title = element_text(size=9), 
                       axis.text = element_text(size=9), 
                       legend.text = element_text(size = 10),
                       legend.key.size = unit(legend_size, "cm"),
                       strip.text = element_text(size=12)  ,
                       panel.grid.minor.x = element_blank(),
                       panel.grid.major.x = element_blank(),
                       panel.grid.minor.y = element_blank(), #element_line(size = 0.25, colour = "#E0E0E0"),
                       panel.grid.major.y = element_blank(), #element_line(size = 0.35, colour = "#DDDDDD"),
                       strip.background = element_rect(colour = 'NA', fill = 'NA'))
    
  } else {
    gr <- gr + theme(  axis.title = element_text(size=9), 
                       axis.text = element_text(size=9), 
                       legend.text = element_text(size = 10),
                       strip.text = element_text(size=12)  ,
                       strip.background = element_rect(colour = 'NA', fill = 'NA'),
                       panel.grid.minor.x = element_blank(),
                       panel.grid.major.x = element_blank(),
                       panel.grid.minor.y = element_blank(), #element_line(size = 0.25, colour = "#E0E0E0"),
                       panel.grid.major.y = element_blank(), #element_line(size = 0.35, colour = "#DDDDDD"),
                       legend.position="none")
  }
  return (gr)
}

gr3=plot_joint_frq(dens_df = slfrq, xlim_s = ROI, legend = T, add_tickbreaks =F, zeroline = F, ybreak=5, ylim_s=FLEN_LIM)
pdf(file=paste0(OUTFN_PREF, '_fl_pos_jnt.pdf'), width = OUTWIDTH, height=OUTHEIGHT)
  print(gr3)
dev.off()
